Repository kowainik/extensions, pull requests merged in 2020-05, with the labels that each got.

#45 [#43] Create CLI tool
  app/Cli.hs
  app/Main.hs
  extensions.cabal
  src/Extensions/OnOff.hs
  test/Test/Extensions.hs
  test/Test/Extensions/Cabal.hs
Labels: CLI, enhancement

#48 [#47] Roundtrip propery tests for OnOffExtension
  extensions.cabal
  src/Extensions/OnOff.hs
  src/Extensions/Parser.hs
  test/Test/Extensions/OnOff.hs
Labels: tests

#51 [#44] Handle Cabal packages without the `hs-source-dirs` field
  src/Extensions/Cabal.hs
  src/Extensions/Parser.hs
  test/Test/Extensions/Parser.hs
Labels: cabal, parser, tests

#50 [#49] Catch CabalException in main functions
  src/Extensions.hs
Labels: cabal

#52 [#39] Support GHC-8.10
  .github/workflows/ci.yml
  extensions.cabal
Labels: CI, enhancement

#53 [#46] Get separate cabal and module Extensions
  src/Extensions.hs
Labels: enhancement

#54 [#6] Write descriptive documentation
  README.md
  src/Extensions.hs
  src/Extensions/Cabal.hs
  src/Extensions/OnOff.hs
  src/Extensions/Parser.hs
Labels: documentation

#56 [#32] Test cabal parsing granularly
  .github/workflows/ci.yml
  src/Extensions/Cabal.hs
  src/Extensions/Parser.hs
  test/Test/Extensions/Cabal.hs
Labels: cabal, tests

#57 [#38] Support SafeHaskell extensions
  app/Main.hs
  extensions.cabal
  src/Extensions.hs
  src/Extensions/Cabal.hs
  src/Extensions/OnOff.hs
  src/Extensions/Parser.hs
  src/Extensions/Types.hs
  test/Test/Extensions.hs
  test/Test/Extensions/Cabal.hs
  test/Test/Extensions/OnOff.hs
  test/Test/Extensions/Parser.hs
Labels: enhancement, safeHaskell

#59 [#58] SafeHaskellExtensions tests
  test/Test/Extensions/Cabal.hs
  test/Test/Extensions/Parser.hs
Labels: safeHaskell, tests

#60 [#55] Move interface into a separate module
  app/Main.hs
  extensions.cabal
  src/Extensions.hs
  src/Extensions/Cabal.hs
  src/Extensions/Module.hs
  src/Extensions/Package.hs
  src/Extensions/Types.hs
  test/Spec.hs
  test/Test/Extensions.hs
  test/Test/Extensions/Cabal.hs
  test/Test/Extensions/Module.hs
  test/Test/Extensions/Types.hs
Labels: documentation, refactoring

#62 [#61] Handle parsing case with comments before LANGUAGE
  CHANGELOG.md
  extensions.cabal
  src/Extensions/Module.hs
  test/Test/Extensions/Module.hs
Labels: parser, tests
